name: airbus
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - colorlog=6.7.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libsqlite=3.41.2
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.3
  - numpy=1.24.3
  - openssl=3.1.0
  - pandas=2.0.1
  - pip=23.1.2
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2023.3
  - readline=8.2
  - setuptools=67.7.2
  - six=1.16.0
  - tk=8.6.12
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - absl-py==1.4.0
      - cachetools==5.3.0
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - cmake==3.26.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - filelock==3.12.0
      - fonttools==4.39.4
      - google-auth==2.18.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.54.0
      - idna==3.4
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - jinja2==3.1.2
      - kiwisolver==1.4.4
      - lit==16.0.3
      - loguru==0.7.0
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.1
      - ninja==1.11.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - onnx==1.14.0
      - onnx-simplifier==0.4.10
      - opencv-python==4.7.0.72
      - packaging==23.1
      - pillow==9.5.0
      - protobuf==4.23.0
      - psutil==5.9.5
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.6
      - pygments==2.15.1
      - pyparsing==3.0.9
      - requests==2.30.0
      - requests-oauthlib==1.3.1
      - rich==13.3.5
      - rsa==4.9
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.0
      - thop==0.1.1-2209072238
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - triton==2.0.0
      - typing-extensions==4.5.0
      - urllib3==1.26.15
      - werkzeug==2.3.4
      - zipp==3.15.0
